### PR TITLE
Windows: build with nlopt from rwinlib

### PR DESCRIPTION
**Pull request by jeroen**
This will allow your package to be built from source on windows by users, build servers or appveyor. Out of the box without setting `NLOPT_HOME` or any other special variables :)

### CODE REVIEW

**Comment by jyypma** [comment]
Many thanks for this, the availability of pre-compiled binaries will be
very helpful!

Some people have expressed worries about security when downloading from an
external site during installation, so I'm a bit hesitant to add this. Do
you know how other packages deal with this (e.g. md5 checksums, optional
downloading)?

In the development version, I have switched to including the NLopt source
code, such that downloading during configure on Unix is no longer
necessary.

**Comment by jeroen** [comment]
It downloads from a secure organization over https, so it is no less secure than installing precompiled R packages from cran mirrors in the same way. [Dozens of packages on CRAN](https://github.com/search?utf8=%E2%9C%93&q=org%3Acran+rwinlib&type=Code) use the same method.

I hope that in a future version of Rtools I can replace this with a proper package manager to download external libs from a special repo. For now we just download the libs directly from github.

**Comment by aadler** [comment]
I've been having troubles trying to get NLOPT 2.6.1 compiled on windows. Actually, I cannot compile anything beyond 2.4.2 without running into errors. @jeroen have you had any success?

**Comment by aadler** [comment]
> 
> 
> I've been having troubles trying to get NLOPT 2.6.1 compiled on windows. Actually, I cannot compile anything beyond 2.4.2 without running into errors. @jeroen have you had any success?

I've worked it out. I'll send a pull request shortly.

**Comment by aadler** [comment]
See https://github.com/jyypma/nloptr/pull/58

**Comment by astamm** [comment]
I and @eddelbuettel did some work to update to the latest version of `nlopt`, use a system build if found or build from shipped source via `cmake` if no existing system build of `nlopt` can be found. This PR is thus probably outdated now. Do you confirm?

**Comment by eddelbuettel** [comment]
Package should be in a good spot now and the (moderate) cost of requiring `cmake` (which most machines including at CRAN appear to have).   By default, NLopt will be built from source.  This is unconditional on macOS and windows, but conditional on Linux where it can be skipped if a recent enough NLopt is found installed.

**Comment by aadler** [comment]
@eddelbuettel Are you still using NLOPT 2.4.2 which separates the C++ library from the C library or have you upgraded to at least 2.6.2, which I am using in my private builds similar to the steps I laid out in https://github.com/astamm/nloptr/pull/58?

**Comment by eddelbuettel** [comment]
"Neither"

@astamm  setup a new system which on all platforms defaults to (via a dependency on `cmake`) building the included 2.7.0 sources.

But I am impatient and know _that on Linux_ dozens of packages do one better and use an existing library if installed.  Which I once contribute to `nloptr` too, and I revisited updated that.   So _on Unix operating systems_ (hence: not yours) if we find `libnlopt` via `pkg-config` _and_ if it is recent enough (I enforce 2.7.0 as minimum for symmetry) we use it.

Hope this helps. It is all in the repo for you to peruse in detail should you choose to do so.

**Comment by astamm** [comment]
I'll close this PR then.

**Comment by eddelbuettel** [comment]
@astamm   This uses a (relative to everything else you have done in the package) outdate binary build of the library.  It could be updated.  I am not sure if reviving this long ignored PR or starting fresh is simpler.  I also do not know if @jeroen is available to help you or not.  Did you email him?

**Comment by jeroen** [comment]
We can easily build a new one if you want, but given that the previous pr hasn't been merged after 4 years I didn't think you would be interested.

**Comment by astamm** [comment]
There has been a switch of maintainer and I happened to see your PR while reviewing them to keep myself up to date (so to speak in this case). I would appreciate the update to then rely on it for building on Windows. I even contributed rwinlib/nlopt#2. Thank you a lot.

**Comment by eddelbuettel** [comment]
Hi @jeroen that may be of interest. There were some transition issues, and some lack of follow-up with the previous maintainer who however did a great job in the R side of things.

A clean build of NLopt 2.7.1 would probably help the new maintainer.

**Comment by aadler** [comment]
@eddelbuettel @jeroen @astamm That would be great. The one missing piece would be to get Tomas Kalibera to add a build into his system so that it is rtools40 and rtools42 compatible, if the new build system is going to be 42 once R URCT for Windows is released.

**Comment by eddelbuettel** [comment]
Yes I made the same comment [here](https://github.com/astamm/nloptr/issues/85#issuecomment-1014664125).

**Comment by kalibera** [comment]
With Rtools42, the only thing you need to do is add "-lnlopt" to your PKG_LIBS in you Makevars.ucrt file, as has been done in the patch I wrote for the package and automatically applied, until removed on the request of the package maintainer (which broke a large number of reverse dependencies).

**Comment by astamm** [comment]
Thanks @kalibera @jeroen @eddelbuettel.
Now, as I am no expert on R for windows, I see that we have [here](https://github.com/r-windows/rtools-packages/tree/b1f3f6e41e01f5eb8c4d1af501d62c5d39c3a1cb/mingw-w64-nlopt) an up-to-date NLopt build for Rtools40.
How should I use that in `nloptr` to make it compatible with both Rtools40 and Rtools42:
- as contributed here by downloading a zip file containing the headers and static libs for both architecture and then use them to properly set up a `Makevars.win` and a `Makevars.ucrt`;
- or using somewhere and somehow `pacman` but that seems more to me a strategy for the end user to help him build easily a system nlopt that would then be directly detected by R on Windows.

So I guess I, as maintainer of the package, should do something more along the lines of my first option. Am I correct?

**Comment by kalibera** [comment]
With Rtools42, which is what CRAN uses, you should not be downloading a pre-built version of nloptr. You should use the version in Rtool42, which is now 2.6.1. Do you need a newer one?

**Comment by aadler** [comment]
@kalibera While the update from 2.6.2 to 2.7 was probably not important, there is a note that 2.7.1 has some minor bugfixes. See https://github.com/stevengj/nlopt/blob/master/NEWS.md.

**Comment by eddelbuettel** [comment]
@kalibera  We went through some hoops to get all other uses up to 2.7.1 so if you could roll the rtools42 version forward that would be appreciated.   @astamm is being chased by CRAN for compilet-time warnings from the older 2.4.*

**Comment by kalibera** [comment]
No problem, I will upgrade, a new version should appear in about an hour. I will also temporarily move the patch back so that you have more time to resolve the warnings without blocking your reverse dependencies (it seems about 1000).

**Pull request closed without merging**
