### PR TITLE
Made configure compliant with Bourne shell (replaced the <<< operator).

### PR DESCRIPTION
**Pull request by yurivict**
Fixed failures on systems where sh != bash.

### CODE REVIEW

**Comment by yurivict** [comment]
Ping. Anybody is there?

**Comment by jyypma** [comment]
Do you still run into the same problem with the latest version of nloptr? I
would think that recent changes have fixed this issue.

**Comment by yurivict** [comment]
The problem is gone, thanks!

**Comment by jyypma** [comment]
Thanks for checking and closing the issue!

**Pull request closed without merging**
