### PR TITLE
added an interface to CCSAQ

### PR DESCRIPTION
**Pull request by jchiquet**
I tried to add an interface to the CCSAQ algorithm, which seems to be included in version 2.4.2 of NLopt.

The example from the new files R/ccsaq.R works for me (R 3.5.1, Ubuntu 18.04 with the system version of nlopt installed via libnlopt-dev), as well as the following code (direct call with nloptr function)

```r
library('nloptr')

##  Solve the Hock-Schittkowski problem no. 100 with analytic gradients
x0.hs100 <- c(1, 2, 0, 4, 0, 1, 1)
fn.hs100 <- function(x) {
    (x[1]-10)^2 + 5*(x[2]-12)^2 + x[3]^4 + 3*(x[4]-11)^2 + 10*x[5]^6 +
        7*x[6]^2 + x[7]^4 - 4*x[6]*x[7] - 10*x[6] - 8*x[7]
}
hin.hs100 <- function(x) {
    h <- numeric(4)
    h[1] <- 127 - 2*x[1]^2 - 3*x[2]^4 - x[3] - 4*x[4]^2 - 5*x[5]
    h[2] <- 282 - 7*x[1] - 3*x[2] - 10*x[3]^2 - x[4] + x[5]
    h[3] <- 196 - 23*x[1] - x[2]^2 - 6*x[6]^2 + 8*x[7]
    h[4] <- -4*x[1]^2 - x[2]^2 + 3*x[1]*x[2] -2*x[3]^2 - 5*x[6]	+11*x[7]
    return(h)
}
gr.hs100 <- function(x) {
    c(  2 * x[1] -  20,
        10 * x[2] - 120,
        4 * x[3]^3,
        6 * x[4] - 66,
        60 * x[5]^5,
        14 * x[6]   - 4 * x[7] - 10,
        4 * x[7]^3 - 4 * x[6] -  8 )}
hinjac.hs100 <- function(x) {
    matrix(c(4*x[1], 12*x[2]^3, 1, 8*x[4], 5, 0, 0,
             7, 3, 20*x[3], 1, -1, 0, 0,
             23, 2*x[2], 0, 0, 0, 12*x[6], -8,
             8*x[1]-3*x[2], 2*x[2]-3*x[1], 4*x[3], 0, 0, 5, -11), 4, 7, byrow=TRUE)
}

res_CCSAQ <- nloptr(
    x0          = x0.hs100, 
    eval_f      = fn.hs100, 
    eval_grad_f = gr.hs100,
    opts        = list("algorithm"="NLOPT_LD_CCSAQ", "xtol_rel"=1.0e-8)
)

res_MMA <- nloptr(
    x0          = x0.hs100, 
    eval_f      = fn.hs100, 
    eval_grad_f = gr.hs100,
    opts        = list("algorithm"="NLOPT_LD_MMA", "xtol_rel" = 1.0e-8)
)
```
with the following outputs

```
> res_MMA

Call:
nloptr(x0 = x0.hs100, eval_f = fn.hs100, eval_grad_f = gr.hs100,     opts = list(algorithm = "NLOPT_LD_MMA", xtol_rel = 1e-08))


Minimization using NLopt version 2.4.2 

NLopt solver status: 4 ( NLOPT_XTOL_REACHED: Optimization stopped because xtol_rel or xtol_abs (above) was reached. )

Number of Iterations....: 53 
Termination conditions:  xtol_rel: 1e-08 
Number of inequality constraints:  0 
Number of equality constraints:    0 
Optimal value of objective function:  -16.0973173946852 
Optimal value of controls: 10 12 0 11 0 1.132329 1.463151


> res_CCSAQ

Call:
nloptr(x0 = x0.hs100, eval_f = fn.hs100, eval_grad_f = gr.hs100,     opts = list(algorithm = "NLOPT_LD_CCSAQ", xtol_rel = 1e-08))



Minimization using NLopt version 2.4.2 

NLopt solver status: 4 ( NLOPT_XTOL_REACHED: Optimization stopped because xtol_rel or xtol_abs (above) was reached. )

Number of Iterations....: 49 
Termination conditions:  xtol_rel: 1e-08 
Number of inequality constraints:  0 
Number of equality constraints:    0 
Optimal value of objective function:  -16.0973173946852 
Optimal value of controls: 10 12 0 11 0 1.132329 1.463151
```

### CODE REVIEW

**Comment by eddelbuettel** [comment]
LGTM from a first glance.

**Comment by jyypma** [comment]
Many thanks for the pull request! At first glance it looks very complete, including tests and documentation, so many thanks for that. I'll take a closer look in a couple of days and will then merge.

**Comment by jchiquet** [comment]
@jyypma Happy to help a bit.

I basically took the example from the documentation file of 'mma.R' by Hans W. Borchers, so he should also be credited.

**Comment by jyypma** [comment]
Merged the pull request and added you as a contributor to the package. Many thanks again!

**Pull request merged**
